default:	emlink intsize magrst magsav mtread mtwrite ptextu strip8 \
			untap untap16 untap_vin utextp

# Unix version of Prime's magrst
magrst: magrst.c istext.c

# Unix version of Prime's magsav
magsav: magsav.c istext.c
